### ISSUE TITLE
enumerateIndices

### ISSUE THREAD

**Issue by seabjackson** [careercup/CtCI-6th-Edition-Swift#12]
Hi I was wondering about how you interated through the String using enumerateIndices on the characters property of the String. My understanding is that we have to iterate through strings in Swift using String.Index, and not an integer. Let me know how you can resolve this

**Comment by matthewcarroll** [comment]
Hello @seabjackson,

Yes, String.Index is the index type for a String in Swift. `enumeratedIndices()` returns a zip where the left element is a String.Index, and the right element is the character.
