### ISSUE TITLE
withMutableCharacters depreciated

### ISSUE THREAD

**Issue by robhasacamera** [careercup/CtCI-6th-Edition-Swift#17]
The method withMutableCharacters is depreciated in the latest version of Swift.

https://developer.apple.com/documentation/swift/string/1538906-withmutablecharacters

https://github.com/careercup/CtCI-6th-Edition-Swift/blob/7afac9bc7848ff460128225686657c9daedd28cc/Ch%201.%20Arrays%20and%20Strings/Ch%201.%20Arrays%20and%20Strings.playground/Pages/1.3%20URLify.xcplaygroundpage/Contents.swift#L18

**Comment by matthewcarroll** [comment]
Thanks. The solutions have been updated to Swift 5.
